server:
  port: 8082
dubbo:
  application:
    name: product_search
  registry:
    address: zookeeper://192.168.135.130:2181
  consumer:
    check: false
#关闭缓存(仅限于开发阶段)
spring:
  thymeleaf:
    cache: false