spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1902_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置数据库连接池为阿里的druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 60000
      filter:
        config:
          enabled: true
  data:
    solr:
      host: http://192.168.135.131/solr

  rabbitmq:
      host: 192.168.135.130
      username: guest
      password: guest
      port: 5672
      virtual-host: /

mybatis:
  mapper-locations: classpath*:com/yj/mapper/*Mapper.xml
  type-aliases-package: com.yj.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: product_search
  registry:
    address: zookeeper://192.168.135.130:2181
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 60000
