spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1902_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置数据库连接池为阿里的druid
    type: com.alibaba.druid.pool.DruidDataSource
    #最大连接数
    druid:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 60000
  #配置消息中间件RabbitMQ
  rabbitmq:
    host: 192.168.135.130
    username: guest
    password: guest
    port: 5672
    virtual-host: /


mybatis:
  mapper-locations: classpath*:com/yj/mapper/*Mapper.xml
  type-aliases-package: com.yj.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: shop_user
  registry:
    protocol: zookeeper
    address: 192.168.135.130:2181
  protocol:
    name: dubbo
    port: -1

